#server.port=8081
#spring.application.name=config-service
#spring.cloud.config.server.git.uri=file:///${user.home}/application-config
#eureka.client.region=default
#eureka.client.registry-fetch-interval-seconds=5
#spring.security.user.name=configUser
#spring.security.user.password=configPassword
#spring.security.user.roles=SYSTEM

server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config